---
- hosts: all
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
  - setup
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600
        delay: 1

    - name: "install python for ansible"
      apt: 
        name: python3
        state: latest
        update_cache: yes

  


