version: 2.1

jobs:

  say-hello:
    docker:
      - image: python:3.10.5-alpine3.16
    # Add steps to the job
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["99:b5:f2:22:73:cc:68:4c:0c:10:a5:30:27:66:37:6d"]
      - run:
          name: "Say hello"
          command: |
            echo "Hello World!"
      - run:
          name: "install openssh"
          command: |
            apk add --update openssh
            apk add --update git

      - run:
          name: "install ansible"
          command: |
            pip install ansible
      - run:
          name: "Run ssh jobs"
          command: |
            ansible-playbook main.yml -i inventory.txt

workflows:
  say-hello-workflow:
    jobs:
      - say-hello