version: 2.1

jobs:
  kreate-server:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run: 
          name: install terraform
          command: |
            apk add --update terraform
      - run: 
          name: set aws environment variables
          command: |
            export AWS_REGION=us-east-1
            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - run:
          name: deploy an instance
          command: |
            cd ../../aws-ec2-instance
            terraform init
      - run:
          name: terraform apply step
          command: |
            cd ../../aws-ec2-instance
            terraform apply

  say-hello:
    docker:
      - image: python:3.10.5-alpine3.16
    # Add steps to the job
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["75:f4:6f:68:2f:45:1e:47:79:3f:4f:9d:98:7a:3c:7b"]
      - run:
          name: "Say hello"
          command: |
            echo "Hello World!"
      - run:
          name: "install openssh"
          command: |
            apk add --update openssh

      - run:
          name: "install ansible"
          command: |
            pip install ansible
      - run:
          name: "Run ssh jobs"
          command: |
            ansible-playbook main.yml -i inventory.txt



workflows:
  say-hello-workflow:
    jobs:
      - kreate-server
      - say-hello:
          requires: [kreate-server]