version: 2.1

jobs:

  say-hello:
    docker:
      - image: python:3.10.5-alpine3.16
    # Add steps to the job
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["75:f4:6f:68:2f:45:1e:47:79:3f:4f:9d:98:7a:3c:7b"]
      - run:
          name: "Say hello"
          command: |
            echo "Hello World!"
      - run:
          name: "install openssh"
          command: |
            apk add --update openssh

      - run:
          name: "install ansible"
          command: |
            pip install ansible
      - run:
          name: "Run ssh jobs"
          command: |
            ansible-playbook main.yml -i inventory.txt



workflows:
  say-hello-workflow:
    jobs:
      - say-hello