version: 2.1

jobs:
  say-hello:
    docker:
      - image: python:3.7
    # Add steps to the job
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: "Run ssh jobs"
          command: |
            cd ..
            ansible-playbook main.yml -i inventory.txt

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
