# playbook plays

- name: "Install Node.js and NPM"
  apt:
    name:
      - "nodejs"
      - "npm"
    state: latest
    update_cache: yes

# roles/setup/tasks/plays.yml

- name: Install web server
  ansible.builtin.apt:
    name: "apache2"
    state: present

- shell: echo "hello world"

- name: install geerlingguy role
  apt: name={{items}} state=installed
  with_items:
    - git

- name: create app directory
  file:
    path: $HOME/webservice
    state: directory
